import type { CourseSubject } from "@/types";

export type SchoolLevel = "ssc" | "hsc";

export const SYLLABUS: Record<SchoolLevel, Partial<Record<CourseSubject, string[]>>> = {
  ssc: {
    Physics: [
      "Chapter 1: Physical Quantities and Measurement",
      "Chapter 2: Motion",
      "Chapter 3: Force",
      "Chapter 4: Work, Power and Energy",
      "Chapter 5: State of Matter and Pressure",
      "Chapter 6: Effect of Heat on Matter",
      "Chapter 7: Waves and Sound",
      "Chapter 8: Reflection of Light",
      "Chapter 9: Refraction of Light",
      "Chapter 10: Static Electricity",
      "Chapter 11: Current Electricity",
      "Chapter 12: Magnetic Effect of Current",
      "Chapter 13: Modern Physics and Electronics",
      "Chapter 14: Physics to Save Life",
    ],
    Chemistry: [
      "Chapter 1: Concept of Chemistry",
      "Chapter 2: States of Matter",
      "Chapter 3: Structure of Matter",
      "Chapter 4: Periodic Table",
      "Chapter 5: Chemical Bonds",
      "Chapter 6: Concept of Mole and Chemical Counting",
      "Chapter 7: Chemical Reactions",
      "Chapter 8: Chemistry and Energy",
      "Chapter 9: Acid-Base Equilibrium",
      "Chapter 10: Mineral Resources: Metal-Nonmetal",
      "Chapter 11: Mineral Resources: Fossil",
      "Chapter 12: Chemistry in Our Lives",
    ],
    Math: [
      "Chapter 1: Real Numbers",
      "Chapter 2: Sets and Functions",
      "Chapter 3: Algebraic Expressions",
      "Chapter 4: Exponents and Logarithms",
      "Chapter 5: Equations with One Variable",
      "Chapter 6: Lines, Angles and Triangles",
      "Chapter 7: Practical Geometry",
      "Chapter 8: Circle",
      "Chapter 9: Trigonometric Ratio",
      "Chapter 10: Distance and Elevation",
      "Chapter 11: Algebraic Ratio and Proportion",
      "Chapter 12: Simple Simultaneous Equations in Two Variables",
      "Chapter 13: Finite Series",
      "Chapter 14: Ratio, Similarity and Symmetry",
      "Chapter 15: Area Related Theorems and Constructions",
      "Chapter 16: Mensuration",
      "Chapter 17: Statistics",
    ],
    "Higher Math": [
      "Chapter 1: Sets and Functions",
      "Chapter 2: Algebraic Expressions",
      "Chapter 3: Geometry",
      "Chapter 4: Geometric Constructions",
      "Chapter 5: Equations",
      "Chapter 6: Inequality",
      "Chapter 7: Infinite Series",
      "Chapter 8: Trigonometry",
      "Chapter 9: Exponential and Logarithmic Functions",
      "Chapter 10: Binomial Expansion",
      "Chapter 11: Coordinate Geometry",
      "Chapter 12: Planar Vector",
      "Chapter 13: Solid Geometry",
      "Chapter 14: Probability",
    ],
    ICT: [
      "Chapter 1: Information and Communication Technology and Our World",
      "Chapter 2: Computer and Computer Security",
      "Chapter 3: Internet in My Education",
      "Chapter 4: My Writing and Calculation",
      "Chapter 5: Multimedia and Graphics",
      "Chapter 6: Database",
    ],
  },
  hsc: {
    Physics: [
      "Chapter 1: Physical World and Measurement",
      "Chapter 2: Vectors",
      "Chapter 3: Dynamics",
      "Chapter 4: Newtonian Mechanics",
      "Chapter 5: Work, Energy and Power",
      "Chapter 6: Gravity and Gravitation",
      "Chapter 7: Structural Properties of Matter",
      "Chapter 8: Periodic Motion",
      "Chapter 9: Waves",
      "Chapter 10: Ideal Gas and Kinetic Theory of Gases",
      "Chapter 1: Thermodynamics",
      "Chapter 2: Static Electricity",
      "Chapter 3: Current Electricity",
      "Chapter 4: Magnetic Effect of Electric Current",
      "Chapter 5: Electromagnetic Induction and Alternating Current",
      "Chapter 6: Geometrical Optics",
      "Chapter 7: Physical Optics",
      "Chapter 8: Introduction to Modern Physics",
      "Chapter 9: Atomic Model and Nuclear Physics",
      "Chapter 10: Semiconductor and Electronics",
      "Chapter 11: Astronomy and Astrophysics",
    ],
    Chemistry: [
      "Chapter 1: Safe Use of Laboratory",
      "Chapter 2: Qualitative Chemistry",
      "Chapter 3: Periodic Properties and Chemical Bond",
      "Chapter 4: Chemical Changes",
      "Chapter 5: Working Chemistry",
      "Chemistry 2nd Paper - Chapter 1: Environmental Chemistry",
      "Chemistry 2nd Paper - Chapter 2: Organic Chemistry",
      "Chemistry 2nd Paper - Chapter 3: Quantitative Chemistry",
      "Chemistry 2nd Paper - Chapter 4: Electrochemistry",
      "Chemistry 2nd Paper - Chapter 5: Economic Chemistry",
    ],
    Math: [
      "Chapter 1: Matrices and Determinants",
      "Chapter 2: Vectors",
      "Chapter 3: Straight Lines",
      "Chapter 4: Circles",
      "Chapter 5: Permutations and Combinations",
      "Chapter 6: Trigonometric Ratios of Associated Angles",
      "Chapter 7: Trigonometric Ratios of Compound Angles",
      "Chapter 8: Functions and Graphs of Functions",
      "Chapter 9: Differentiation",
      "Chapter 10: Integration",
      "Chapter 1: Real Numbers and Inequalities",
      "Chapter 2: Linear Programming",
      "Chapter 3: Complex Numbers",
      "Chapter 4: Polynomials and Polynomial Equations",
      "Chapter 5: Binomial Expansion",
      "Chapter 6: Conics",
      "Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations",
      "Chapter 8: Statics",
      "Chapter 9: Dynamics of Particles in a Plane",
      "Chapter 10: Probability",
    ],
    "Higher Math": [
      "Chapter 1: Matrices and Determinants",
      "Chapter 2: Vectors",
      "Chapter 3: Straight Lines",
      "Chapter 4: Circles",
      "Chapter 5: Permutations and Combinations",
      "Chapter 6: Trigonometric Ratios of Associated Angles",
      "Chapter 7: Trigonometric Ratios of Compound Angles",
      "Chapter 8: Functions and Graphs of Functions",
      "Chapter 9: Differentiation",
      "Chapter 10: Integration",
      "Chapter 1: Real Numbers and Inequalities",
      "Chapter 2: Linear Programming",
      "Chapter 3: Complex Numbers",
      "Chapter 4: Polynomials and Polynomial Equations",
      "Chapter 5: Binomial Expansion",
      "Chapter 6: Conics",
      "Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations",
      "Chapter 8: Statics",
      "Chapter 9: Dynamics of Particles in a Plane",
      "Chapter 10: Probability",
    ],
    ICT: [
      "Chapter 1: Information and Communication Technology: World and Bangladesh Perspective",
      "Chapter 2: Communication Systems and Networking",
      "Chapter 3: Number Systems and Digital Devices",
      "Chapter 4: Introduction to Web Design and HTML",
      "Chapter 5: Programming Language",
      "Chapter 6: Database Management System",
    ],
    "Physics 1st Paper": [
      "Chapter 1: Physical World and Measurement",
      "Chapter 2: Vectors",
      "Chapter 3: Dynamics",
      "Chapter 4: Newtonian Mechanics",
      "Chapter 5: Work, Energy and Power",
      "Chapter 6: Gravity and Gravitation",
      "Chapter 7: Structural Properties of Matter",
      "Chapter 8: Periodic Motion",
      "Chapter 9: Waves",
      "Chapter 10: Ideal Gas and Kinetic Theory of Gases",
    ],
    "Physics 2nd Paper": [
      "Chapter 1: Thermodynamics",
      "Chapter 2: Static Electricity",
      "Chapter 3: Current Electricity",
      "Chapter 4: Magnetic Effect of Electric Current",
      "Chapter 5: Electromagnetic Induction and Alternating Current",
      "Chapter 6: Geometrical Optics",
      "Chapter 7: Physical Optics",
      "Chapter 8: Introduction to Modern Physics",
      "Chapter 9: Atomic Model and Nuclear Physics",
      "Chapter 10: Semiconductor and Electronics",
      "Chapter 11: Astronomy and Astrophysics",
    ],
    "Chemistry 1st Paper": [
      "Chapter 1: Safe Use of Laboratory",
      "Chapter 2: Qualitative Chemistry",
      "Chapter 3: Periodic Properties and Chemical Bond",
      "Chapter 4: Chemical Changes",
      "Chapter 5: Working Chemistry",
    ],
    "Chemistry 2nd Paper": [
      "Chemistry 2nd Paper - Chapter 1: Environmental Chemistry",
      "Chemistry 2nd Paper - Chapter 2: Organic Chemistry",
      "Chemistry 2nd Paper - Chapter 3: Quantitative Chemistry",
      "Chemistry 2nd Paper - Chapter 4: Electrochemistry",
      "Chemistry 2nd Paper - Chapter 5: Economic Chemistry",
    ],
    "Higher Math 1st Paper": [
      "Chapter 1: Matrices and Determinants",
      "Chapter 2: Vectors",
      "Chapter 3: Straight Lines",
      "Chapter 4: Circles",
      "Chapter 5: Permutations and Combinations",
      "Chapter 6: Trigonometric Ratios of Associated Angles",
      "Chapter 7: Trigonometric Ratios of Compound Angles",
      "Chapter 8: Functions and Graphs of Functions",
      "Chapter 9: Differentiation",
      "Chapter 10: Integration",
    ],
    "Higher Math 2nd Paper": [
      "Chapter 1: Real Numbers and Inequalities",
      "Chapter 2: Linear Programming",
      "Chapter 3: Complex Numbers",
      "Chapter 4: Polynomials and Polynomial Equations",
      "Chapter 5: Binomial Expansion",
      "Chapter 6: Conics",
      "Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations",
      "Chapter 8: Statics",
      "Chapter 9: Dynamics of Particles in a Plane",
      "Chapter 10: Probability",
    ],
  },
};

export function getSchoolLevel(studentClass: string): SchoolLevel {
  if (studentClass === "class-9" || studentClass === "class-10") {
    return "ssc";
  }
  return "hsc";
}

// ──────────────────────────────────────────────────
// Bangla chapter name translations
// ──────────────────────────────────────────────────
export const CHAPTER_TRANSLATIONS: Record<string, string> = {
  // SSC Physics
  "Chapter 1: Physical Quantities and Measurement": "অধ্যায় ১: ভৌত রাশি ও পরিমাপ",
  "Chapter 2: Motion": "অধ্যায় ২: গতি",
  "Chapter 3: Force": "অধ্যায় ৩: বল",
  "Chapter 4: Work, Power and Energy": "অধ্যায় ৪: কাজ, ক্ষমতা ও শক্তি",
  "Chapter 5: State of Matter and Pressure": "অধ্যায় ৫: পদার্থের অবস্থা ও চাপ",
  "Chapter 6: Effect of Heat on Matter": "অধ্যায় ৬: বস্তুর উপর তাপের প্রভাব",
  "Chapter 7: Waves and Sound": "অধ্যায় ৭: তরঙ্গ ও শব্দ",
  "Chapter 8: Reflection of Light": "অধ্যায় ৮: আলোর প্রতিফলন",
  "Chapter 9: Refraction of Light": "অধ্যায় ৯: আলোর প্রতিসরণ",
  "Chapter 10: Static Electricity": "অধ্যায় ১০: স্থির বিদ্যুৎ",
  "Chapter 11: Current Electricity": "অধ্যায় ১১: চল বিদ্যুৎ",
  "Chapter 12: Magnetic Effect of Current": "অধ্যায় ১২: বিদ্যুতের চৌম্বক প্রভাব",
  "Chapter 13: Modern Physics and Electronics": "অধ্যায় ১৩: আধুনিক পদার্থবিজ্ঞান ও ইলেকট্রনিক্স",
  "Chapter 14: Physics to Save Life": "অধ্যায় ১৪: জীবন রক্ষায় পদার্থবিজ্ঞান",
  // SSC Chemistry
  "Chapter 1: Concept of Chemistry": "অধ্যায় ১: রসায়নের ধারণা",
  "Chapter 2: States of Matter": "অধ্যায় ২: পদার্থের অবস্থা",
  "Chapter 3: Structure of Matter": "অধ্যায় ৩: পদার্থের গঠন",
  "Chapter 4: Periodic Table": "অধ্যায় ৪: পর্যায় সারণি",
  "Chapter 5: Chemical Bonds": "অধ্যায় ৫: রাসায়নিক বন্ধন",
  "Chapter 6: Concept of Mole and Chemical Counting": "অধ্যায় ৬: মোলের ধারণা ও রাসায়নিক গণনা",
  "Chapter 7: Chemical Reactions": "অধ্যায় ৭: রাসায়নিক বিক্রিয়া",
  "Chapter 8: Chemistry and Energy": "অধ্যায় ৮: রসায়ন ও শক্তি",
  "Chapter 9: Acid-Base Equilibrium": "অধ্যায় ৯: অ্যাসিড-ক্ষার সাম্যাবস্থা",
  "Chapter 10: Mineral Resources: Metal-Nonmetal": "অধ্যায় ১০: খনিজ সম্পদ: ধাতু-অধাতু",
  "Chapter 11: Mineral Resources: Fossil": "অধ্যায় ১১: খনিজ সম্পদ: জীবাশ্ম",
  "Chapter 12: Chemistry in Our Lives": "অধ্যায় ১২: আমাদের জীবনে রসায়ন",
  // SSC Math
  "Chapter 1: Real Numbers": "অধ্যায় ১: বাস্তব সংখ্যা",
  "Chapter 2: Sets and Functions": "অধ্যায় ২: সেট ও ফাংশন",
  "Chapter 3: Algebraic Expressions": "অধ্যায় ৩: বীজগাণিতিক রাশি",
  "Chapter 4: Exponents and Logarithms": "অধ্যায় ৪: সূচক ও লগারিদম",
  "Chapter 5: Equations with One Variable": "অধ্যায় ৫: এক চলকবিশিষ্ট সমীকরণ",
  "Chapter 6: Lines, Angles and Triangles": "অধ্যায় ৬: রেখা, কোণ ও ত্রিভুজ",
  "Chapter 7: Practical Geometry": "অধ্যায় ৭: ব্যবহারিক জ্যামিতি",
  "Chapter 8: Circle": "অধ্যায় ৮: বৃত্ত",
  "Chapter 9: Trigonometric Ratio": "অধ্যায় ৯: ত্রিকোণমিতিক অনুপাত",
  "Chapter 10: Distance and Elevation": "অধ্যায় ১০: দূরত্ব ও উচ্চতা",
  "Chapter 11: Algebraic Ratio and Proportion": "অধ্যায় ১১: বীজগাণিতিক অনুপাত ও সমানুপাত",
  "Chapter 12: Simple Simultaneous Equations in Two Variables": "অধ্যায় ১২: দুই চলকবিশিষ্ট সরল সমীকরণ",
  "Chapter 13: Finite Series": "অধ্যায় ১৩: সীমিত ধারা",
  "Chapter 14: Ratio, Similarity and Symmetry": "অধ্যায় ১৪: অনুপাত, সদৃশতা ও প্রতিসাম্য",
  "Chapter 15: Area Related Theorems and Constructions": "অধ্যায় ১৫: ক্ষেত্রফল সংক্রান্ত উপপাদ্য ও অঙ্কন",
  "Chapter 16: Mensuration": "অধ্যায় ১৬: পরিমিতি",
  "Chapter 17: Statistics": "অধ্যায় ১৭: পরিসংখ্যান",
  // SSC Higher Math
  "Chapter 1: Sets and Functions": "অধ্যায় ১: সেট ও ফাংশন",
  "Chapter 6: Inequality": "অধ্যায় ৬: অসমতা",
  "Chapter 7: Infinite Series": "অধ্যায় ৭: অসীম ধারা",
  "Chapter 8: Trigonometry": "অধ্যায় ৮: ত্রিকোণমিতি",
  "Chapter 9: Exponential and Logarithmic Functions": "অধ্যায় ৯: সূচকীয় ও লগারিদমীয় ফাংশন",
  "Chapter 10: Binomial Expansion": "অধ্যায় ১০: দ্বিপদী বিস্তৃতি",
  "Chapter 11: Coordinate Geometry": "অধ্যায় ১১: স্থানাঙ্ক জ্যামিতি",
  "Chapter 12: Planar Vector": "অধ্যায় ১২: সমতলীয় ভেক্টর",
  "Chapter 13: Solid Geometry": "অধ্যায় ১৩: ত্রিমাত্রিক জ্যামিতি",
  "Chapter 14: Probability": "অধ্যায় ১৪: সম্ভাবনা",
  // SSC ICT
  "Chapter 1: Information and Communication Technology and Our World": "অধ্যায় ১: তথ্য ও যোগাযোগ প্রযুক্তি এবং আমাদের বিশ্ব",
  "Chapter 2: Computer and Computer Security": "অধ্যায় ২: কম্পিউটার ও কম্পিউটার নিরাপত্তা",
  "Chapter 3: Internet in My Education": "অধ্যায় ৩: আমার শিক্ষায় ইন্টারনেট",
  "Chapter 4: My Writing and Calculation": "অধ্যায় ৪: আমার লেখা ও হিসাব",
  "Chapter 5: Multimedia and Graphics": "অধ্যায় ৫: মাল্টিমিডিয়া ও গ্রাফিক্স",
  "Chapter 6: Database": "অধ্যায় ৬: ডেটাবেস",
  // HSC Physics 1st Paper
  "Chapter 1: Physical World and Measurement": "অধ্যায় ১: ভৌত জগৎ ও পরিমাপ",
  "Chapter 2: Vectors": "অধ্যায় ২: ভেক্টর",
  "Chapter 3: Dynamics": "অধ্যায় ৩: গতিবিদ্যা",
  "Chapter 4: Newtonian Mechanics": "অধ্যায় ৪: নিউটনীয় বলবিদ্যা",
  "Chapter 5: Work, Energy and Power": "অধ্যায় ৫: কাজ, শক্তি ও ক্ষমতা",
  "Chapter 6: Gravity and Gravitation": "অধ্যায় ৬: মহাকর্ষ ও অভিকর্ষ",
  "Chapter 7: Structural Properties of Matter": "অধ্যায় ৭: পদার্থের গাঠনিক ধর্ম",
  "Chapter 8: Periodic Motion": "অধ্যায় ৮: পর্যায়বৃত্ত গতি",
  "Chapter 9: Waves": "অধ্যায় ৯: তরঙ্গ",
  "Chapter 10: Ideal Gas and Kinetic Theory of Gases": "অধ্যায় ১০: আদর্শ গ্যাস ও গ্যাসের গতীয় তত্ত্ব",
  // HSC Physics 2nd Paper
  "Chapter 1: Thermodynamics": "অধ্যায় ১: তাপগতিবিদ্যা",
  "Chapter 2: Static Electricity": "অধ্যায় ২: স্থির বিদ্যুৎ",
  "Chapter 3: Current Electricity": "অধ্যায় ৩: চল বিদ্যুৎ",
  "Chapter 4: Magnetic Effect of Electric Current": "অধ্যায় ৪: তড়িৎ প্রবাহের চৌম্বক প্রভাব",
  "Chapter 5: Electromagnetic Induction and Alternating Current": "অধ্যায় ৫: তড়িৎচুম্বকীয় আবেশ ও পরিবর্তী প্রবাহ",
  "Chapter 6: Geometrical Optics": "অধ্যায় ৬: জ্যামিতিক আলোকবিজ্ঞান",
  "Chapter 7: Physical Optics": "অধ্যায় ৭: ভৌত আলোকবিজ্ঞান",
  "Chapter 8: Introduction to Modern Physics": "অধ্যায় ৮: আধুনিক পদার্থবিজ্ঞানের সূচনা",
  "Chapter 9: Atomic Model and Nuclear Physics": "অধ্যায় ৯: পরমাণু মডেল ও নিউক্লিয়ার পদার্থবিজ্ঞান",
  "Chapter 10: Semiconductor and Electronics": "অধ্যায় ১০: অর্ধপরিবাহী ও ইলেকট্রনিক্স",
  "Chapter 11: Astronomy and Astrophysics": "অধ্যায় ১১: জ্যোতির্বিজ্ঞান ও জ্যোতিঃপদার্থবিজ্ঞান",
  // HSC Chemistry 1st Paper
  "Chapter 1: Safe Use of Laboratory": "অধ্যায় ১: গবেষণাগারের নিরাপদ ব্যবহার",
  "Chapter 2: Qualitative Chemistry": "অধ্যায় ২: গুণগত রসায়ন",
  "Chapter 3: Periodic Properties and Chemical Bond": "অধ্যায় ৩: পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন",
  "Chapter 4: Chemical Changes": "অধ্যায় ৪: রাসায়নিক পরিবর্তন",
  "Chapter 5: Working Chemistry": "অধ্যায় ৫: কর্মক্ষেত্রে রসায়ন",
  // HSC Chemistry 2nd Paper
  "Chapter 1: Environmental Chemistry": "অধ্যায় ১: পরিবেশ রসায়ন",
  "Chapter 2: Organic Chemistry": "অধ্যায় ২: জৈব রসায়ন",
  "Chapter 3: Quantitative Chemistry": "অধ্যায় ৩: পরিমাণগত রসায়ন",
  "Chapter 4: Electrochemistry": "অধ্যায় ৪: তড়িৎ রসায়ন",
  "Chapter 5: Economic Chemistry": "অধ্যায় ৫: শিল্প রসায়ন",
  // HSC Math 1st Paper
  "Chapter 1: Matrices and Determinants": "অধ্যায় ১: ম্যাট্রিক্স ও নির্ণায়ক",
  "Chapter 2: Vector": "অধ্যায় ২: ভেক্টর",
  "Chapter 3: Straight Lines": "অধ্যায় ৩: সরলরেখা",
  "Chapter 4: Circles": "অধ্যায় ৪: বৃত্ত",
  "Chapter 5: Permutations and Combinations": "অধ্যায় ৫: বিন্যাস ও সমাবেশ",
  "Chapter 6: Trigonometric Ratios of Associated Angles": "অধ্যায় ৬: সংযুক্ত কোণের ত্রিকোণমিতিক অনুপাত",
  "Chapter 7: Trigonometric Ratios of Compound Angles": "অধ্যায় ৭: যৌগিক কোণের ত্রিকোণমিতিক অনুপাত",
  "Chapter 8: Functions and Graphs of Functions": "অধ্যায় ৮: ফাংশন ও ফাংশনের লেখচিত্র",
  "Chapter 9: Differentiation": "অধ্যায় ৯: অন্তরীকরণ",
  "Chapter 10: Integration": "অধ্যায় ১০: যোগজীকরণ",
  // HSC Math 2nd Paper
  "Chapter 1: Real Numbers and Inequalities": "অধ্যায় ১: বাস্তব সংখ্যা ও অসমতা",
  "Chapter 2: Linear Programming": "অধ্যায় ২: যোগাশ্রয়ী প্রোগ্রাম",
  "Chapter 3: Complex Numbers": "অধ্যায় ৩: জটিল সংখ্যা",
  "Chapter 4: Polynomials and Polynomial Equations": "অধ্যায় ৪: বহুপদী ও বহুপদী সমীকরণ",
  "Chapter 5: Binomial Expansion": "অধ্যায় ৫: দ্বিপদী বিস্তৃতি",
  "Chapter 6: Conics": "অধ্যায় ৬: কনিক",
  "Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations": "অধ্যায় ৭: বিপরীত ত্রিকোণমিতিক ফাংশন ও ত্রিকোণমিতিক সমীকরণ",
  "Chapter 8: Statics": "অধ্যায় ৮: স্থিতিবিদ্যা",
  "Chapter 9: Dynamics of Particles in a Plane": "অধ্যায় ৯: সমতলে বস্তুকণার গতি",
  "Chapter 10: Probability": "অধ্যায় ১০: সম্ভাবনা",
  // HSC ICT
  "Chapter 1: Information and Communication Technology: World and Bangladesh Perspective": "অধ্যায় ১: তথ্য ও যোগাযোগ প্রযুক্তি: বিশ্ব ও বাংলাদেশ প্রেক্ষিত",
  "Chapter 2: Communication Systems and Networking": "অধ্যায় ২: যোগাযোগ ব্যবস্থা ও নেটওয়ার্কিং",
  "Chapter 3: Number Systems and Digital Devices": "অধ্যায় ৩: সংখ্যা পদ্ধতি ও ডিজিটাল ডিভাইস",
  "Chapter 4: Introduction to Web Design and HTML": "অধ্যায় ৪: ওয়েব ডিজাইন পরিচিতি ও HTML",
  "Chapter 5: Programming Language": "অধ্যায় ৫: প্রোগ্রামিং ভাষা",
  "Chapter 6: Database Management System": "অধ্যায় ৬: ডেটাবেস ম্যানেজমেন্ট সিস্টেম",
};

export function getTranslatedChapter(chapter: string, locale?: string): string {
  return CHAPTER_TRANSLATIONS[chapter] ?? chapter;
}

export const BENGALI_TO_ENGLISH_SUBJECT_MAP: Record<string, string> = {
  "পদার্থবিজ্ঞান": "Physics",
  "পদার্থবিজ্ঞান ১ম পত্র": "Physics 1st Paper",
  "পদার্থবিজ্ঞান ২য় পত্র": "Physics 2nd Paper",
  "রসায়ন": "Chemistry",
  "রসায়ন ১ম পত্র": "Chemistry 1st Paper",
  "রসায়ন ২য় পত্র": "Chemistry 2nd Paper",
  "সাধারণ গণিত": "Math",
  "উচ্চতর গণিত": "Higher Math",
  "উচ্চতর গণিত ১ম পত্র": "Higher Math 1st Paper",
  "উচ্চতর গণিত ২য় পত্র": "Higher Math 2nd Paper",
  "তথ্য ও যোগাযোগ প্রযুক্তি": "ICT",
};

export function getSyllabusChapters(level: SchoolLevel, subject: string): string[] {
  const canonicalSubject = BENGALI_TO_ENGLISH_SUBJECT_MAP[subject] || subject;
  return SYLLABUS[level]?.[canonicalSubject as CourseSubject] || [];
}

export const SSC_MCQ_SUBJECTS = [
  "পদার্থবিজ্ঞান",
  "রসায়ন",
  "সাধারণ গণিত",
  "উচ্চতর গণিত",
  "জীববিজ্ঞান",
  "তথ্য ও যোগাযোগ প্রযুক্তি",
  "বাংলা ১ম পত্র",
  "বাংলা ২য় পত্র",
  "ইংরেজি ১ম পত্র",
  "ইংরেজি ২য় পত্র",
  "ইসলাম ও নৈতিক শিক্ষা",
  "বাংলাদেশ ও বিশ্বপরিচয়",
];

export const HSC_MCQ_SUBJECTS = [
  "পদার্থবিজ্ঞান ১ম পত্র",
  "পদার্থবিজ্ঞান ২য় পত্র",
  "রসায়ন ১ম পত্র",
  "রসায়ন ২য় পত্র",
  "উচ্চতর গণিত ১ম পত্র",
  "উচ্চতর গণিত ২য় পত্র",
  "জীববিজ্ঞান ১ম পত্র",
  "জীববিজ্ঞান ২য় পত্র",
  "তথ্য ও যোগাযোগ প্রযুক্তি",
  "বাংলা ১ম পত্র",
  "বাংলা ২য় পত্র",
  "ইংরেজি ১ম পত্র",
  "ইংরেজি ২য় পত্র",
];

export const COURSE_TO_MCQ_SUBJECT_MAP: Record<"ssc" | "hsc", Record<string, string[]>> = {
  ssc: {
    Physics: ["পদার্থবিজ্ঞান"],
    Chemistry: ["রসায়ন"],
    Math: ["সাধারণ গণিত"],
    "Higher Math": ["উচ্চতর গণিত"],
    ICT: ["তথ্য ও যোগাযোগ প্রযুক্তি"],
  },
  hsc: {
    Physics: ["পদার্থবিজ্ঞান ১ম পত্র", "পদার্থবিজ্ঞান ২য় পত্র"],
    Chemistry: ["রসায়ন ১ম পত্র", "রসায়ন ২য় পত্র"],
    "Higher Math": ["উচ্চতর গণিত ১ম পত্র", "উচ্চতর গণিত ২য় পত্র"],
    ICT: ["তথ্য ও যোগাযোগ প্রযুক্তি"],
  },
};
