import type { CourseSubject } from "@/types";

export type SchoolLevel = "ssc" | "hsc";

export const SYLLABUS: Record<SchoolLevel, Record<CourseSubject, string[]>> = {
  ssc: {
    Physics: [
      "Chapter 1: Physical Quantities and Measurement",
      "Chapter 2: Motion",
      "Chapter 3: Force",
      "Chapter 4: Work, Power and Energy",
      "Chapter 5: State of Matter and Pressure",
      "Chapter 6: Effect of Heat on Matter",
      "Chapter 7: Waves and Sound",
      "Chapter 8: Reflection of Light",
      "Chapter 9: Refraction of Light",
      "Chapter 10: Static Electricity",
      "Chapter 11: Current Electricity",
      "Chapter 12: Magnetic Effect of Current",
      "Chapter 13: Modern Physics and Electronics",
      "Chapter 14: Physics to Save Life",
    ],
    Chemistry: [
      "Chapter 1: Concept of Chemistry",
      "Chapter 2: States of Matter",
      "Chapter 3: Structure of Matter",
      "Chapter 4: Periodic Table",
      "Chapter 5: Chemical Bonds",
      "Chapter 6: Concept of Mole and Chemical Counting",
      "Chapter 7: Chemical Reactions",
      "Chapter 8: Chemistry and Energy",
      "Chapter 9: Acid-Base Equilibrium",
      "Chapter 10: Mineral Resources: Metal-Nonmetal",
      "Chapter 11: Mineral Resources: Fossil",
      "Chapter 12: Chemistry in Our Lives",
    ],
    Math: [
      "Chapter 1: Real Numbers",
      "Chapter 2: Sets and Functions",
      "Chapter 3: Algebraic Expressions",
      "Chapter 4: Exponents and Logarithms",
      "Chapter 5: Equations with One Variable",
      "Chapter 6: Lines, Angles and Triangles",
      "Chapter 7: Practical Geometry",
      "Chapter 8: Circle",
      "Chapter 9: Trigonometric Ratio",
      "Chapter 10: Distance and Elevation",
      "Chapter 11: Algebraic Ratio and Proportion",
      "Chapter 12: Simple Simultaneous Equations in Two Variables",
      "Chapter 13: Finite Series",
      "Chapter 14: Ratio, Similarity and Symmetry",
      "Chapter 15: Area Related Theorems and Constructions",
      "Chapter 16: Mensuration",
      "Chapter 17: Statistics",
    ],
    "Higher Math": [
      "Chapter 1: Sets and Functions",
      "Chapter 2: Algebraic Expressions",
      "Chapter 3: Geometry",
      "Chapter 4: Geometric Constructions",
      "Chapter 5: Equations",
      "Chapter 6: Inequality",
      "Chapter 7: Infinite Series",
      "Chapter 8: Trigonometry",
      "Chapter 9: Exponential and Logarithmic Functions",
      "Chapter 10: Binomial Expansion",
      "Chapter 11: Coordinate Geometry",
      "Chapter 12: Planar Vector",
      "Chapter 13: Solid Geometry",
      "Chapter 14: Probability",
    ],
    ICT: [
      "Chapter 1: Information and Communication Technology and Our World",
      "Chapter 2: Computer and Computer Security",
      "Chapter 3: Internet in My Education",
      "Chapter 4: My Writing and Calculation",
      "Chapter 5: Multimedia and Graphics",
      "Chapter 6: Database",
    ],
  },
  hsc: {
    Physics: [
      "Physics 1st Paper - Chapter 1: Physical World and Measurement",
      "Physics 1st Paper - Chapter 2: Vectors",
      "Physics 1st Paper - Chapter 3: Dynamics",
      "Physics 1st Paper - Chapter 4: Newtonian Mechanics",
      "Physics 1st Paper - Chapter 5: Work, Energy and Power",
      "Physics 1st Paper - Chapter 6: Gravity and Gravitation",
      "Physics 1st Paper - Chapter 7: Structural Properties of Matter",
      "Physics 1st Paper - Chapter 8: Periodic Motion",
      "Physics 1st Paper - Chapter 9: Waves",
      "Physics 1st Paper - Chapter 10: Ideal Gas and Kinetic Theory of Gases",
      "Physics 2nd Paper - Chapter 1: Thermodynamics",
      "Physics 2nd Paper - Chapter 2: Static Electricity",
      "Physics 2nd Paper - Chapter 3: Current Electricity",
      "Physics 2nd Paper - Chapter 4: Magnetic Effect of Electric Current",
      "Physics 2nd Paper - Chapter 5: Electromagnetic Induction and Alternating Current",
      "Physics 2nd Paper - Chapter 6: Geometrical Optics",
      "Physics 2nd Paper - Chapter 7: Physical Optics",
      "Physics 2nd Paper - Chapter 8: Introduction to Modern Physics",
      "Physics 2nd Paper - Chapter 9: Atomic Model and Nuclear Physics",
      "Physics 2nd Paper - Chapter 10: Semiconductor and Electronics",
      "Physics 2nd Paper - Chapter 11: Astronomy and Astrophysics",
    ],
    Chemistry: [
      "Chemistry 1st Paper - Chapter 1: Safe Use of Laboratory",
      "Chemistry 1st Paper - Chapter 2: Qualitative Chemistry",
      "Chemistry 1st Paper - Chapter 3: Periodic Properties and Chemical Bond",
      "Chemistry 1st Paper - Chapter 4: Chemical Changes",
      "Chemistry 1st Paper - Chapter 5: Working Chemistry",
      "Chemistry 2nd Paper - Chapter 1: Environmental Chemistry",
      "Chemistry 2nd Paper - Chapter 2: Organic Chemistry",
      "Chemistry 2nd Paper - Chapter 3: Quantitative Chemistry",
      "Chemistry 2nd Paper - Chapter 4: Electrochemistry",
      "Chemistry 2nd Paper - Chapter 5: Economic Chemistry",
    ],
    Math: [
      "Mathematics 1st Paper - Chapter 1: Matrices and Determinants",
      "Mathematics 1st Paper - Chapter 2: Vectors",
      "Mathematics 1st Paper - Chapter 3: Straight Lines",
      "Mathematics 1st Paper - Chapter 4: Circles",
      "Mathematics 1st Paper - Chapter 5: Permutations and Combinations",
      "Mathematics 1st Paper - Chapter 6: Trigonometric Ratios of Associated Angles",
      "Mathematics 1st Paper - Chapter 7: Trigonometric Ratios of Compound Angles",
      "Mathematics 1st Paper - Chapter 8: Functions and Graphs of Functions",
      "Mathematics 1st Paper - Chapter 9: Differentiation",
      "Mathematics 1st Paper - Chapter 10: Integration",
      "Mathematics 2nd Paper - Chapter 1: Real Numbers and Inequalities",
      "Mathematics 2nd Paper - Chapter 2: Linear Programming",
      "Mathematics 2nd Paper - Chapter 3: Complex Numbers",
      "Mathematics 2nd Paper - Chapter 4: Polynomials and Polynomial Equations",
      "Mathematics 2nd Paper - Chapter 5: Binomial Expansion",
      "Mathematics 2nd Paper - Chapter 6: Conics",
      "Mathematics 2nd Paper - Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations",
      "Mathematics 2nd Paper - Chapter 8: Statics",
      "Mathematics 2nd Paper - Chapter 9: Dynamics of Particles in a Plane",
      "Mathematics 2nd Paper - Chapter 10: Probability",
    ],
    "Higher Math": [
      "Mathematics 1st Paper - Chapter 1: Matrices and Determinants",
      "Mathematics 1st Paper - Chapter 2: Vectors",
      "Mathematics 1st Paper - Chapter 3: Straight Lines",
      "Mathematics 1st Paper - Chapter 4: Circles",
      "Mathematics 1st Paper - Chapter 5: Permutations and Combinations",
      "Mathematics 1st Paper - Chapter 6: Trigonometric Ratios of Associated Angles",
      "Mathematics 1st Paper - Chapter 7: Trigonometric Ratios of Compound Angles",
      "Mathematics 1st Paper - Chapter 8: Functions and Graphs of Functions",
      "Mathematics 1st Paper - Chapter 9: Differentiation",
      "Mathematics 1st Paper - Chapter 10: Integration",
      "Mathematics 2nd Paper - Chapter 1: Real Numbers and Inequalities",
      "Mathematics 2nd Paper - Chapter 2: Linear Programming",
      "Mathematics 2nd Paper - Chapter 3: Complex Numbers",
      "Mathematics 2nd Paper - Chapter 4: Polynomials and Polynomial Equations",
      "Mathematics 2nd Paper - Chapter 5: Binomial Expansion",
      "Mathematics 2nd Paper - Chapter 6: Conics",
      "Mathematics 2nd Paper - Chapter 7: Inverse Trigonometric Functions and Trigonometric Equations",
      "Mathematics 2nd Paper - Chapter 8: Statics",
      "Mathematics 2nd Paper - Chapter 9: Dynamics of Particles in a Plane",
      "Mathematics 2nd Paper - Chapter 10: Probability",
    ],
    ICT: [
      "Chapter 1: Information and Communication Technology: World and Bangladesh Perspective",
      "Chapter 2: Communication Systems and Networking",
      "Chapter 3: Number Systems and Digital Devices",
      "Chapter 4: Introduction to Web Design and HTML",
      "Chapter 5: Programming Language",
      "Chapter 6: Database Management System",
    ],
  },
};

export function getSchoolLevel(studentClass: string): SchoolLevel {
  if (studentClass === "class-9" || studentClass === "class-10") {
    return "ssc";
  }
  return "hsc";
}
