sonar.projectKey=Mostafijur-1_Al-Biruni-Study-Point
sonar.projectName=Al-Biruni Study Point
sonar.projectVersion=0.1.0

sonar.sourceEncoding=UTF-8
sonar.sources=app,components,hooks,lib,stores
sonar.typescript.tsconfigPaths=tsconfig.json

sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/build/**,**/coverage/**,public/**,lib/data/practice/**
